---
# tasks file for myvhost
- name: install httpd
  yum:
    name: latest
    state: latest

- name: start and enable httpd service
  service:
    name: http
    state: started
    enabled: true
- name: deliver html cmontent
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd

