---
- name: Install and start Apache HTTPD
  hosts: web
  become: yes
  gather_facts: no
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
      tags: install-web

    - name: correct index.html is present
      template:
        src: files/index.html.j2
        dest: /var/www/html/index.html
      #ignore_errors: yes  

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
    
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
      tags: firewall  

    - name: Update httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        line: 'Listen 8080'
      ignore_errors: yes
      notify: httpd is restarted
   
  handlers: 
    - name: httpd is restarted
      service:
        name: httpd
        state: restarted



    




