---
- hosts: web
  user: ansible
  become: true
  vars:
    system_owner: info@ziyotek.local

  tasks:
    - template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
         